[package]
name = "netrunner-logger"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

[lib]
path = "src/lib.rs"

[dependencies]
log = "0.4"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json"] }
regex = "1.10"

[target.'cfg(target_os = "android")'.dependencies]
tracing-android = "0.2"

[features]
default = []
